// Golden (RunSelection -> args, display) pairs, generated by running the
// real src/electron/public/shared/command.mjs under `node` against the same
// inputs. Regenerate with:
//
//   cd src/electron && node --input-type=module -e '...' (see git history /
//   session notes for the exact script) and paste the new cases in below.
//
// Not a bundle resource — Phase 0 found CLT/SwiftPM doing surprising things
// to the test target, and Bundle.module is one more thing that can break for
// reasons unrelated to the code under test.
import Testing
@testable import SbxKit

struct ParityCase: CustomTestStringConvertible {
    let label: String
    let selection: RunSelection
    let expectedArgs: [String]
    let expectedDisplay: String
    var testDescription: String { label }
}

enum ParityCorpus {
    static let commandCases: [ParityCase] = [
        ParityCase(
            label: "target example",
            selection: RunSelection(
                agent: "claude", template: "claude-sbx-dotnet10:v2", name: nil, clone: false,
                editable: ["/path/to/NHO.0476.ConsentRegister.Web"],
                readOnly: ["/path/to/NHO.AccessHub.Web"], primary: nil
            ),
            expectedArgs: [
                "sbx", "run", "--template", "claude-sbx-dotnet10:v2", "claude",
                "/path/to/NHO.0476.ConsentRegister.Web", "/path/to/NHO.AccessHub.Web:ro",
            ],
            expectedDisplay: "sbx run --template claude-sbx-dotnet10:v2 claude "
                + "/path/to/NHO.0476.ConsentRegister.Web /path/to/NHO.AccessHub.Web:ro"
        ),
        ParityCase(
            label: "multi editable/readonly, explicit primary",
            selection: RunSelection(
                agent: "claude", template: "tpl", name: nil, clone: false,
                editable: ["/root/B", "/root/A"], readOnly: ["/root/D", "/root/C"], primary: "/root/A"
            ),
            expectedArgs: ["sbx", "run", "--template", "tpl", "claude", "/root/A", "/root/B", "/root/C:ro", "/root/D:ro"],
            expectedDisplay: "sbx run --template tpl claude /root/A /root/B /root/C:ro /root/D:ro"
        ),
        ParityCase(
            label: "name and clone before agent",
            selection: RunSelection(
                agent: "claude", template: "tpl:v1", name: "my-sandbox", clone: true,
                editable: ["/root/A"], readOnly: [], primary: nil
            ),
            expectedArgs: ["sbx", "run", "--template", "tpl:v1", "--name", "my-sandbox", "--clone", "claude", "/root/A"],
            expectedDisplay: "sbx run --template tpl:v1 --name my-sandbox --clone claude /root/A"
        ),
        ParityCase(
            label: "ro suffix inside quotes for spaced path",
            selection: RunSelection(
                agent: "claude", template: "tpl", name: nil, clone: false,
                editable: ["/root/A"], readOnly: ["/path/with space"], primary: nil
            ),
            expectedArgs: ["sbx", "run", "--template", "tpl", "claude", "/root/A", "/path/with space:ro"],
            expectedDisplay: "sbx run --template tpl claude /root/A '/path/with space:ro'"
        ),
        ParityCase(
            label: "unpromoted primary falls back to default",
            selection: RunSelection(
                agent: "claude", template: "tpl", name: nil, clone: false,
                editable: ["/root/B", "/root/A"], readOnly: [], primary: "/root/Z"
            ),
            expectedArgs: ["sbx", "run", "--template", "tpl", "claude", "/root/A", "/root/B"],
            expectedDisplay: "sbx run --template tpl claude /root/A /root/B"
        ),
        ParityCase(
            label: "name with whitespace trimmed",
            selection: RunSelection(
                agent: "claude", template: "tpl", name: "  spaced-name  ", clone: false,
                editable: ["/root/A"], readOnly: [], primary: nil
            ),
            expectedArgs: ["sbx", "run", "--template", "tpl", "--name", "spaced-name", "claude", "/root/A"],
            expectedDisplay: "sbx run --template tpl --name spaced-name claude /root/A"
        ),
        ParityCase(
            label: "single quote in path",
            selection: RunSelection(
                agent: "claude", template: "tpl", name: nil, clone: false,
                editable: ["/it's/here"], readOnly: [], primary: nil
            ),
            expectedArgs: ["sbx", "run", "--template", "tpl", "claude", "/it's/here"],
            expectedDisplay: "sbx run --template tpl claude '/it'\\''s/here'"
        ),
        ParityCase(
            label: "three editable, alpha-ordered after primary",
            selection: RunSelection(
                agent: "claude", template: "tpl", name: nil, clone: false,
                editable: ["/root/C", "/root/A", "/root/B"], readOnly: [], primary: "/root/B"
            ),
            expectedArgs: ["sbx", "run", "--template", "tpl", "claude", "/root/B", "/root/A", "/root/C"],
            expectedDisplay: "sbx run --template tpl claude /root/B /root/A /root/C"
        ),
        ParityCase(
            label: "no name no clone",
            selection: RunSelection(
                agent: "opencode", template: "tpl:v3", name: nil, clone: false,
                editable: ["/root/A"], readOnly: [], primary: nil
            ),
            expectedArgs: ["sbx", "run", "--template", "tpl:v3", "opencode", "/root/A"],
            expectedDisplay: "sbx run --template tpl:v3 opencode /root/A"
        ),
        ParityCase(
            label: "empty string name treated as absent",
            selection: RunSelection(
                agent: "claude", template: "tpl", name: "", clone: false,
                editable: ["/root/A"], readOnly: [], primary: nil
            ),
            expectedArgs: ["sbx", "run", "--template", "tpl", "claude", "/root/A"],
            expectedDisplay: "sbx run --template tpl claude /root/A"
        ),
        ParityCase(
            label: "multiple readOnly sorted",
            selection: RunSelection(
                agent: "claude", template: "tpl", name: nil, clone: false,
                editable: ["/root/A"], readOnly: ["/root/Z", "/root/B", "/root/M"], primary: nil
            ),
            expectedArgs: ["sbx", "run", "--template", "tpl", "claude", "/root/A", "/root/B:ro", "/root/M:ro", "/root/Z:ro"],
            expectedDisplay: "sbx run --template tpl claude /root/A /root/B:ro /root/M:ro /root/Z:ro"
        ),
        ParityCase(
            label: "clone without name",
            selection: RunSelection(
                agent: "claude", template: "tpl", name: nil, clone: true,
                editable: ["/root/A"], readOnly: [], primary: nil
            ),
            expectedArgs: ["sbx", "run", "--template", "tpl", "--clone", "claude", "/root/A"],
            expectedDisplay: "sbx run --template tpl --clone claude /root/A"
        ),
        ParityCase(
            label: "NFD path (combining ring above)",
            selection: RunSelection(
                agent: "claude", template: "tpl", name: nil, clone: false,
                editable: ["/root/A\u{030A}"], readOnly: [], primary: nil
            ),
            expectedArgs: ["sbx", "run", "--template", "tpl", "claude", "/root/A\u{030A}"],
            expectedDisplay: "sbx run --template tpl claude '/root/A\u{030A}'"
        ),
        ParityCase(
            label: "safe unquoted colon in path not just template",
            selection: RunSelection(
                agent: "claude", template: "repo:v1", name: nil, clone: false,
                editable: ["/root/A:B"], readOnly: [], primary: nil
            ),
            expectedArgs: ["sbx", "run", "--template", "repo:v1", "claude", "/root/A:B"],
            expectedDisplay: "sbx run --template repo:v1 claude /root/A:B"
        ),
    ]
}
